pragma Singleton
import QtQuick
import "."

/**
 * @brief Design tokens — single point of access for all themed values.
 *
 * Three sub-namespaces:
 * - `Theme.color.*` — wallpaper-driven colors (delegates to `ColorTokens`,
 *   regenerated by matugen on wallpaper change, gitignored)
 * - `Theme.font.*`  — typography (static, lives in this file)
 * - `Theme.anim.*`  — motion durations (static, lives in this file)
 *
 * Future expansion (spacing, radius, elevation) lands here as new
 * sub-namespaces without touching matugen.
 */
QtObject {
    /// Wallpaper-driven colors — delegates to `ColorTokens` (regenerated by matugen).
    readonly property QtObject color: QtObject {
        readonly property color windowBg: ColorTokens.windowBg
        readonly property color popupBg: ColorTokens.popupBg
        readonly property color moduleBg: ColorTokens.moduleBg
        readonly property color border: ColorTokens.border
        readonly property color text: ColorTokens.text
        readonly property color textMuted: ColorTokens.textMuted
        readonly property color accent: ColorTokens.accent
        readonly property color alert: ColorTokens.alert
    }

    /// Typography tokens.
    readonly property QtObject font: QtObject {
        /// Font family used everywhere — NerdFont required for icon glyphs
        readonly property string family: "Iosevka Nerd Font"
        /// Smaller text size for tooltips and hints
        readonly property int sizeSm: 14
        /// Default text size for module labels
        readonly property int sizeMd: 18
        /// Larger text size for emphasized labels (clock, layouts)
        readonly property int sizeLg: 20
    }

    /// Motion / animation durations (ms).
    readonly property QtObject anim: QtObject {
        /// Color / hover transitions
        readonly property int fast: 150
        /// Popup pop-in, longer effects
        readonly property int slow: 300
    }
}