-- Hyprland — Rayane
-- https://wiki.hyprland.org/Configuring/
-- Entry point. Source order matters: vars before binds that use them.

-- ── Variables ─────────────────────────────────────────────────────────────────
-- Adapt to your stack.
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

mod = "SUPER"
terminal = "footclient"
fileManager = "footclient -e superfile"
browser = "firefox"
menu = "walker"
lock = "hyprlock"

-- ── Environment ───────────────────────────────────────────────────────────────
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_THEME", "Bibata-Modern-Amber")
hl.env("XKB_DEFAULT_LAYOUT", "fr")
-- amd/mesa: eglDupNativeFenceFDANDROID bug → tearing without this
hl.env("AQ_DRM_NO_EXPLICIT_SYNC", "1")

-- ── Modules ───────────────────────────────────────────────────────────────────
-- Source: ~/.config/hypr/modules/monitors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.monitors")
-- Source: ~/.config/hypr/modules/input.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.input")
-- Source: ~/.config/hypr/modules/decoration.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.decoration")
-- Source: ~/.config/hypr/modules/rules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.rules")
-- Source: ~/.config/hypr/modules/binds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.binds")
-- Source: ~/.config/hypr/modules/autostart.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.autostart")
