# Hyprpaper — wallpapers
# https://wiki.hyprland.org/Hypr-Ecosystem/hyprpaper/

preload = /etc/nixos/wallpapers/dp2.jpg
preload = /etc/nixos/wallpapers/dp1.jpg

wallpaper = DP-2,/etc/nixos/wallpapers/dp2.jpg
wallpaper = DP-1,/etc/nixos/wallpapers/dp1.jpg

splash = false
ipc = on
