-- ── Autostart ─────────────────────────────────────────────────────────────────
-- Daemons (foot --server, awww-daemon, dunst, hypridle, swayosd, nm-applet,
-- easyeffects, wl-clip-persist, cliphist, hyprpolkitagent) and the initial
-- wallpaper are systemd user services bound to graphical-session.target —
-- see home.nix. UWSM starts that target when this Hyprland session enters
-- its systemd scope, so nothing needs to be exec-once'd here.
--
-- Only scripts that talk to Hyprland's own socket stay here.

-- Steam pins notification toasts to X primary
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Nothing is launched from here any more, not even the two scripts that talk to
-- Hyprland's own socket: hl.on("hyprland.start") fires before UWSM exports
-- HYPRLAND_INSTANCE_SIGNATURE, so hyprctl fails and both scripts died on the
-- spot under `set -e`. They are xrandr-primary.service and
-- hypr-orientation.service, ordered after graphical-session.target — see home.nix.
