-- ── Autostart ─────────────────────────────────────────────────────────────────
-- Daemons (foot --server, awww-daemon, dunst, hypridle, swayosd, nm-applet,
-- easyeffects, wl-clip-persist, cliphist, hyprpolkitagent) and the initial
-- wallpaper are systemd user services bound to graphical-session.target —
-- see home.nix. UWSM starts that target when this Hyprland session enters
-- its systemd scope, so nothing needs to be exec-once'd here.
--
-- Only scripts that talk to Hyprland's own socket stay here.

-- Steam pins notification toasts to X primary
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- master orientation follows active monitor (portrait → top, landscape → left)

hl.on("hyprland.start", function()
	hl.exec_cmd("/etc/nixos/hypr/scripts/xrandr-primary.sh")
	hl.exec_cmd("/etc/nixos/hypr/scripts/orientation-daemon.sh")
end)
