-- ── Autostart ─────────────────────────────────────────────────────────────────
-- Daemons (foot --server, awww-daemon, dunst, hypridle, swayosd, nm-applet,
-- easyeffects, wl-clip-persist, cliphist, hyprpolkitagent) and the initial
-- wallpaper are systemd user services bound to graphical-session.target —
-- see home.nix. UWSM starts that target when this Hyprland session enters
-- its systemd scope, so nothing needs to be exec-once'd here.
--
-- Only scripts that talk to Hyprland's own socket stay here.

-- Steam pins notification toasts to X primary
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- master orientation (portrait → top, landscape → left) is hypr-orientation.service:
-- this event fires before UWSM exports HYPRLAND_INSTANCE_SIGNATURE, so the daemon
-- could never reach the compositor's IPC socket from here. See home.nix.

hl.on("hyprland.start", function()
	hl.exec_cmd("/etc/nixos/hypr/scripts/xrandr-primary.sh")
end)
