-- ── Keybinds ──────────────────────────────────────────────────────────────────
-- Prefixes:  bindm = mouse  ·  bindl = works while locked  ·  bindel = locked+repeat
--            bindp = bypasses keyboard-shortcut inhibitors (needed inside games)
-- Requires:  swayosd-client, grim+slurp+wl-copy, playerctl, ~/Screenshots/

-- Apps
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.bind(mod .. " + Return", hl.dsp.exec_cmd(terminal))
hl.bind(mod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mod .. " + B", hl.dsp.exec_cmd(browser))
hl.bind(mod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mod .. " + SHIFT + Return", hl.dsp.exec_cmd(menu))
hl.bind(mod .. " + L", hl.dsp.exec_cmd("loginctl lock-session"))
hl.bind(mod .. " + SHIFT + T", hl.dsp.exec_cmd("tidal-hifi"))
hl.bind(mod .. " + D", hl.dsp.exec_cmd("vesktop"))

-- Cycle wallpaper on DP-2 + regenerate theme via matugen
hl.bind(mod .. " + W", hl.dsp.exec_cmd("/etc/nixos/hypr/scripts/wallpaper-cycle.sh next"))
hl.bind(mod .. " + SHIFT + W", hl.dsp.exec_cmd("/etc/nixos/hypr/scripts/wallpaper-cycle.sh prev"))

hl.bind(mod .. " + SHIFT + R", hl.dsp.exec_cmd("hyprctl reload"))

-- Toggle HDR on the OLED for HDR games (desktop stays SDR otherwise so capture works).
-- bindp: must fire even while a Proton game grabs keyboard shortcuts.
hl.bind(mod .. " + SHIFT + H", hl.dsp.exec_cmd("/etc/nixos/hypr/scripts/hdr-toggle.sh"), { dont_inhibit = true })

-- Two subtleties to make this work inside games:
--   1. `p` flag: ignores keyboard_shortcuts_inhibit_v1 (Proton via
--      winewayland.drv otherwise eats the bind on focus).
--   2. Script reloads full kb_layout instead of `hyprctl switchxkblayout` —
--      emits a fresh wl_keyboard.keymap so games that cached the initial one
--      pick up the change. (Dropped xkb grp:win_space_toggle for the same reason.)
hl.bind(mod .. " + space", hl.dsp.exec_cmd("/etc/nixos/hypr/scripts/kb-layout-toggle.sh"), { dont_inhibit = true })

-- Window
hl.bind(mod .. " + A", hl.dsp.window.close())
hl.bind(mod .. " + SHIFT + A", hl.dsp.window.kill())
hl.bind(mod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mod .. " + SHIFT + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind(mod .. " + P", hl.dsp.window.pseudo())
hl.bind(mod .. " + J", hl.dsp.layout("togglesplit"))

-- Exit Hyprland
hl.bind(mod .. " + SHIFT + M", hl.dsp.exit())

-- Focus (vim-keys + arrows)
hl.bind(mod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mod .. " + down", hl.dsp.focus({ direction = "down" }))
hl.bind(mod .. " + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mod .. " + l", hl.dsp.focus({ direction = "right" }))
hl.bind(mod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mod .. " + j", hl.dsp.focus({ direction = "down" }))

-- Swap windows
hl.bind(mod .. " + SHIFT + left", hl.dsp.window.swap({ direction = "l" }))
hl.bind(mod .. " + SHIFT + right", hl.dsp.window.swap({ direction = "r" }))
hl.bind(mod .. " + SHIFT + up", hl.dsp.window.swap({ direction = "u" }))
hl.bind(mod .. " + SHIFT + down", hl.dsp.window.swap({ direction = "d" }))

-- AZERTY workspace row — Shift-less keys are punctuation, not digits
-- 1=&  2=é  3="  4='  5=(  6=-  7=è  8=_  9=ç
hl.bind(mod .. " + ampersand", hl.dsp.focus({ workspace = 1 }))
hl.bind(mod .. " + eacute", hl.dsp.focus({ workspace = 2 }))
hl.bind(mod .. " + quotedbl", hl.dsp.focus({ workspace = 3 }))
hl.bind(mod .. " + apostrophe", hl.dsp.focus({ workspace = 4 }))
hl.bind(mod .. " + parenleft", hl.dsp.focus({ workspace = 5 }))
hl.bind(mod .. " + minus", hl.dsp.focus({ workspace = 6 }))
hl.bind(mod .. " + egrave", hl.dsp.focus({ workspace = 7 }))
hl.bind(mod .. " + underscore", hl.dsp.focus({ workspace = 8 }))
hl.bind(mod .. " + ccedilla", hl.dsp.focus({ workspace = 9 }))
-- direct digits — keypad + QWERTY fallback
hl.bind(mod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mod .. " + 9", hl.dsp.focus({ workspace = 9 }))

-- Move window to workspace — AZERTY row
hl.bind(mod .. " + SHIFT + ampersand", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mod .. " + SHIFT + eacute", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mod .. " + SHIFT + quotedbl", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mod .. " + SHIFT + apostrophe", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mod .. " + SHIFT + parenleft", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mod .. " + SHIFT + minus", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mod .. " + SHIFT + egrave", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mod .. " + SHIFT + underscore", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mod .. " + SHIFT + ccedilla", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))

-- Cycle workspaces
hl.bind(mod .. " + Tab", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mod .. " + SHIFT + Tab", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Mouse drag/resize
hl.bind(mod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mod .. " + mouse:273", hl.dsp.window.resize())

-- Screenshots
hl.bind(mod .. " + S", hl.dsp.exec_cmd("sh -c 'grim -g \"$(slurp)\" ~/Screenshots/screen-$(date +%Y%m%d-%H%M%S).png'"))
hl.bind(mod .. " + CTRL + S", hl.dsp.exec_cmd("sh -c 'grim -g \"$(slurp)\" - | tee /tmp/screen.png | wl-copy'"))

-- Volume (swayosd)
hl.bind(
	"XF86AudioRaiseVolume",
	hl.dsp.exec_cmd("swayosd-client --output-volume raise"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioLowerVolume",
	hl.dsp.exec_cmd("swayosd-client --output-volume lower"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMute",
	hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMicMute",
	hl.dsp.exec_cmd("swayosd-client --input-volume mute-toggle"),
	{ locked = true, repeating = true }
)

-- Brightness
hl.bind(
	"XF86MonBrightnessUp",
	hl.dsp.exec_cmd("swayosd-client --brightness raise"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86MonBrightnessDown",
	hl.dsp.exec_cmd("swayosd-client --brightness lower"),
	{ locked = true, repeating = true }
)

-- Media
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
