-- ── Monitors ──────────────────────────────────────────────────────────────────
-- Matched on EDID desc — DP-X names shift across boots.
-- Desktop kept SDR: an HDR output can't be captured (portal/grim return black, no
-- tonemap). HDR is enabled per-game via gamescope --hdr-enabled in Steam launch opts,
-- which scopes it to the game window only. bitdepth 10 keeps SDR gradients banding-free.
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
	output = "desc:Dell Inc. AW3423DWF 5LKG2S3",
	mode = "3440x1440@164.9",
	position = "1080x0",
	scale = "1",
	bitdepth = 10,
})

hl.monitor({
	output = "desc:AOC 24G1WG4 0x000076A8",
	mode = "1920x1080@144",
	position = "0x0",
	scale = "1",
	transform = 3,
})

hl.monitor({
	output = "",
	mode = "preferred",
	position = "auto",
	scale = "1",
})

-- ── Workspaces per monitor ────────────────────────────────────────────────────
-- 1-7 on the OLED (primary), 8-9 on the portrait
hl.workspace_rule({
	workspace = "1",
	monitor = "desc:Dell Inc. AW3423DWF 5LKG2S3",
	default = true,
})

hl.workspace_rule({
	workspace = "2",
	monitor = "desc:Dell Inc. AW3423DWF 5LKG2S3",
})

hl.workspace_rule({
	workspace = "3",
	monitor = "desc:Dell Inc. AW3423DWF 5LKG2S3",
})

hl.workspace_rule({
	workspace = "4",
	monitor = "desc:Dell Inc. AW3423DWF 5LKG2S3",
})

hl.workspace_rule({
	workspace = "5",
	monitor = "desc:Dell Inc. AW3423DWF 5LKG2S3",
})

hl.workspace_rule({
	workspace = "6",
	monitor = "desc:Dell Inc. AW3423DWF 5LKG2S3",
})

hl.workspace_rule({
	workspace = "7",
	monitor = "desc:Dell Inc. AW3423DWF 5LKG2S3",
})

hl.workspace_rule({
	workspace = "8",
	monitor = "desc:AOC 24G1WG4 0x000076A8",
	default = true,
})

hl.workspace_rule({
	workspace = "9",
	monitor = "desc:AOC 24G1WG4 0x000076A8",
})
