-- ── Window rules ──────────────────────────────────────────────────────────────
-- Block syntax — Hyprland 0.54+

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
	name = "pavucontrol-float",
	match = {
		class = "^(pavucontrol)$",
	},
	float = true,
})

hl.window_rule({
	name = "blueman-float",
	match = {
		class = "^(blueman-manager)$",
	},
	float = true,
})

hl.window_rule({
	name = "nmce-float",
	match = {
		class = "^(nm-connection-editor)$",
	},
	float = true,
})

hl.window_rule({
	name = "foot-opacity",
	match = {
		class = "^(foot)$",
	},
	opacity = "0.9 0.85",
})

hl.window_rule({
	name = "steam-float",
	match = {
		class = "^(steam)$",
	},
	float = true,
})
