pragma Singleton
import QtQuick

// Theme tokens — single source of truth for colors, durations, fonts.
// Palette is regenerated by matugen from the current wallpaper.
QtObject {
    readonly property color bg0: "#161217"
    readonly property color bg1: "#1e1a1f"
    readonly property color bg2: "#231e23"
    readonly property color bg3: "#2d282e"
    readonly property color fg1: "#e9e0e7"
    readonly property color fg4: "#cec3ce"
    readonly property color yellow: "#e3b7f4"
    readonly property color red: "#ffb4ab"

    readonly property int animFast: 150
    readonly property int animSlow: 300

    readonly property string fontFamily: "Iosevka Nerd Font"
    readonly property int fontSizeMd: 18
    readonly property int fontSizeLg: 20
}
