pragma Singleton
import QtQuick

QtObject {
    // Generated by matugen from current wallpaper
    readonly property color bg0: "#1a1110"
    readonly property color bg1: "#231918"
    readonly property color bg2: "#271d1c"
    readonly property color bg3: "#322826"
    readonly property color fg1: "#f1dfdb"
    readonly property color fg4: "#d8c2be"
    readonly property color yellow: "#ffb4a7"
    readonly property color red: "#ffb4ab"

    readonly property int animFast: 150
    readonly property int animSlow: 300

    readonly property string fontFamily: "Iosevka Nerd Font"
    readonly property int fontSizeMd: 18
    readonly property int fontSizeLg: 20
}
