pragma Singleton
import QtQuick

// Theme tokens — single source of truth for colors, durations, fonts.
// Color palette is regenerated by matugen from the current wallpaper.
QtObject {
    /// Window / bar background — the darkest base
    readonly property color windowBg: "#131318"
    /// Popout container background — Calendar, Tidal, Power
    readonly property color popupBg: "#1b1b21"
    /// Module idle / tooltip background
    readonly property color moduleBg: "#1f1f25"
    /// Subtle borders and separators
    readonly property color border: "#2a292f"

    /// Primary text on dark backgrounds
    readonly property color text: "#e4e1e9"
    /// Secondary / muted text
    readonly property color textMuted: "#c7c5d0"

    /// Accent — active states, highlights
    readonly property color accent: "#bfc2ff"
    /// Alert — urgent / error states
    readonly property color alert: "#ffb4ab"

    /// Fast animation duration (ms) — color/hover transitions
    readonly property int animFast: 150
    /// Slow animation duration (ms) — popup pop-in, longer effects
    readonly property int animSlow: 300

    /// Font family used everywhere — NerdFont required for icon glyphs
    readonly property string fontFamily: "Iosevka Nerd Font"
    /// Default text size for module labels
    readonly property int fontSizeMd: 18
    /// Larger text size for emphasized labels (clock, layouts)
    readonly property int fontSizeLg: 20
}
