pragma Singleton
import QtQuick

// Color palette — regenerated by matugen from the current wallpaper.
// All non-color tokens (font, anim, spacing, …) live in services/Theme.qml.
QtObject {
    /// Window / bar background — the darkest base
    readonly property color windowBg: "{{colors.surface.default.hex}}"
    /// Popout container background — Calendar, Tidal, Power
    readonly property color popupBg: "{{colors.surface_container_low.default.hex}}"
    /// Module idle / tooltip background
    readonly property color moduleBg: "{{colors.surface_container.default.hex}}"
    /// Subtle borders and separators
    readonly property color border: "{{colors.surface_container_high.default.hex}}"

    /// Primary text on dark backgrounds
    readonly property color text: "{{colors.on_surface.default.hex}}"
    /// Secondary / muted text
    readonly property color textMuted: "{{colors.on_surface_variant.default.hex}}"

    /// Accent — active states, highlights
    readonly property color accent: "{{colors.primary.default.hex}}"
    /// Alert — urgent / error states
    readonly property color alert: "{{colors.error.default.hex}}"
}
