pragma Singleton
import QtQuick

// Theme tokens — single source of truth for colors, durations, fonts.
// Color palette is regenerated by matugen from the current wallpaper.
QtObject {
    /// Window / bar background — the darkest base
    readonly property color windowBg: "{{colors.surface.default.hex}}"
    /// Popout container background — Calendar, Tidal, Power
    readonly property color popupBg: "{{colors.surface_container_low.default.hex}}"
    /// Module idle / tooltip background
    readonly property color moduleBg: "{{colors.surface_container.default.hex}}"
    /// Subtle borders and separators
    readonly property color border: "{{colors.surface_container_high.default.hex}}"

    /// Primary text on dark backgrounds
    readonly property color text: "{{colors.on_surface.default.hex}}"
    /// Secondary / muted text
    readonly property color textMuted: "{{colors.on_surface_variant.default.hex}}"

    /// Accent — active states, highlights
    readonly property color accent: "{{colors.primary.default.hex}}"
    /// Alert — urgent / error states
    readonly property color alert: "{{colors.error.default.hex}}"

    /// Fast animation duration (ms) — color/hover transitions
    readonly property int animFast: 150
    /// Slow animation duration (ms) — popup pop-in, longer effects
    readonly property int animSlow: 300

    /// Font family used everywhere — NerdFont required for icon glyphs
    readonly property string fontFamily: "Iosevka Nerd Font"
    /// Default text size for module labels
    readonly property int fontSizeMd: 18
    /// Larger text size for emphasized labels (clock, layouts)
    readonly property int fontSizeLg: 20
}
